### ISSUE TITLE
v0.0.2にアップデートすると起動直後に落ちるようになった。

### ISSUE THREAD

**Issue by okajun35** [gottadiveintopython/chumon_kesan_support#10]
アップデート後、起動直後に落ちるようになりました。
具体的には、アプリをタップして起動、Lodaing画面が表示、その後落ちてスマホのホーム画面に戻るという症状です。
ログは取得していません。週末時間があったら取得してみます。

何回か動作して同じところで落ちるので、おそらくフォントかファイルを呼ぼうとして、落ちているようです。※v0.0.1でメニューと注文表を登録しています。

よろしくお願いします。

**Comment by gottadiveintopython** [comment]
こっちでは同じ症状が起きず原因が分からないので、logを見せてもらえると助かります。 m(_ _)m

**Comment by okajun35** [comment]
遅くなりましたがログ取ってみました。ご確認ください。

10615行目あたりでエラーになってます。ちなみにアンドロイドの実機で2台あったので試してみましたら2台とも起動直後にエラーになってます。

[log.txt](https://github.com/gottadiveintopython/chumon_kesan_support/files/3780906/log.txt)

エラーの部分は以下です
```
10-29 07:22:16.505 24122 24144 I python  : Android kivy bootstrap done. __name__ is __main__
10-29 07:22:16.505 24122 24144 I python  : AND: Ran string
10-29 07:22:16.505 24122 24144 I python  : Run user program, change dir and execute entrypoint
10-29 07:22:16.511  2168  2226 W libprocessgroup: kill(-18319, 9) failed: No such process
10-29 07:22:16.519  1064  1064 I Zygote  : Process 18319 exited due to signal (9)
10-29 07:22:16.522  2168 12521 W ActivityManager: Scheduling restart of crashed service jp.co.johospace.jorte/com.jorte.dprofiler.DprofilerService in 1000ms
10-29 07:22:16.527 13349 13349 D LauncherAppWidgetHost: setListenIfResumed :false, mFlags:7
10-29 07:22:16.527 13349 13349 D LauncherAppWidgetHost: stopListening
10-29 07:22:16.528 13349 13349 W RecentsModel: onTrimMemory level = 20
10-29 07:22:16.536  2168  2226 W libprocessgroup: kill(-18319, 9) failed: No such process
10-29 07:22:16.536  2168  2226 I libprocessgroup: Successfully killed process cgroup uid 10155 pid 18319 in 25ms
10-29 07:22:16.541 15657 23652 I PBSessionCacheImpl: Deleted sessionId[68861786445800866] from persistence.
10-29 07:22:16.563 15657 15676 W SearchServiceCore: Abort, client detached.
10-29 07:22:16.563 15657 15676 W SearchServiceCore: Abort, client detached.
10-29 07:22:16.584 15657 15676 I StreamController: cleanUpControllerScope(nowcards-15-16014898-6175)
10-29 07:22:16.586 15657 15676 W SearchServiceCore: Abort, client detached.
10-29 07:22:16.617  1217  2518 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen jp.gottadiveintopython.chumon_kesan#0
10-29 07:22:16.617  1217  2518 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen jp.gottadiveintopython.chumon_kesan#0
10-29 07:22:16.660 13349 13360 I orola.launcher: Background concurrent copying GC freed 278361(46MB) AllocSpace objects, 0(0B) LOS objects, 46% free, 27MB/51MB, paused 222us total 159.791ms
10-29 07:22:16.874 24122 24144 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/jp.gottadiveintopython.chumon_kesan/files/app/.kivy/logs/kivy_19-10-29_1.txt
10-29 07:22:16.875 24122 24144 I python  : [INFO   ] [Kivy        ] v1.11.1
10-29 07:22:16.875 24122 24144 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/jp.gottadiveintopython.chumon_kesan/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
10-29 07:22:16.875 24122 24144 I python  : [INFO   ] [Python      ] v3.7.1 (default, Oct 24 2019, 03:32:11) 
10-29 07:22:16.875 24122 24144 I python  : [Clang 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55
10-29 07:22:16.876 24122 24144 I python  : [INFO   ] [Python      ] Interpreter at "android_python"
10-29 07:22:16.894 24122 24144 I python  : [ERROR  ] [Clock       ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
10-29 07:22:16.895 24122 24144 I python  :  Traceback (most recent call last):
10-29 07:22:16.895 24122 24144 I python  :    File "/tmp/firefox/chumon_kesan/.buildozer/android/app/main.py", line 2, in <module>
10-29 07:22:16.896 24122 24144 I python  :    File "/tmp/firefox/chumon_kesan/.buildozer/android/app/chumon_kesan/__init__.py", line 8, in main
10-29 07:22:16.897 24122 24144 I python  :    File "/tmp/firefox/chumon_kesan/.buildozer/android/platform/build/build/python-installs/chumon_kesan/kivy/app.py", line 319, in <module>
10-29 07:22:16.898 24122 24144 I python  :    File "/tmp/firefox/chumon_kesan/.buildozer/android/platform/build/build/python-installs/chumon_kesan/kivy/base.py", line 26, in <module>
10-29 07:22:16.898 24122 24144 I python  :    File "/tmp/firefox/chumon_kesan/.buildozer/android/platform/build/build/python-installs/chumon_kesan/kivy/clock.py", line 363, in <module>
10-29 07:22:16.899 24122 24144 I python  :  ImportError: dlopen failed: "/data/data/jp.gottadiveintopython.chumon_kesan/files/app/_python_bundle/site-packages/kivy/_clock.so" is 32-bit instead of 64-bit
10-29 07:22:16.899 24122 24144 I python  : Python for android ended.
10-29 07:22:16.902 13349 13360 I orola.launcher: Background concurrent copying GC freed 267898(44MB) AllocSpace objects, 0(0B) LOS objects, 50% free, 23MB/47MB, paused 319us total 111.888ms
10-29 07:22:17.067  2168  2483 W InputDispatcher: channel '7105018 jp.gottadiveintopython.chumon_kesan/org.kivy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-29 07:22:17.067  2168  2483 E InputDispatcher: channel '7105018 jp.gottadiveintopython.chumon_kesan/org.kivy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-29 07:22:17.068  2168 10504 I ActivityManager: Process jp.gottadiveintopython.chumon_kesan (pid 24122) has died: fore TOP 
10-29 07:22:17.068  2168  2226 W libprocessgroup: kill(-24122, 9) failed: No such process
10-29 07:22:17.068  2168 10504 W ActivityManager: Force removing ActivityRecord{17ee1da u0 jp.gottadiveintopython.chumon_kesan/org.kivy.android.PythonActivity t6803}: app died, no saved state
10-29 07:22:17.071  1064  1064 I Zygote  : Process 24122 exited cleanly (255)
10-29 07:22:17.071  2168 17434 I WindowManager: WIN DEATH: Window{7105018 u0 jp.gottadiveintopython.chumon_kesan/org.kivy.android.PythonActivity}
10-29 07:22:17.071  2168 17434 W InputDispatcher: Attempted to unregister already unregistered input channel '7105018 jp.gottadiveintopython.chumon_kesan/org.kivy.android.PythonActivity (server)'
10-29 07:22:17.084  1217  2902 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{4b7dce8 token=Token{472c60b ActivityRecord{17ee1da u0 jp.gottadiveintopython.chumon_kesan/org.kivy.android.PythonActivity t6803}}}#0
10-29 07:22:17.086  2168 10504 I ActivityManager: moveHomeStack, setupComplete:true
10-29 07:22:17.090  2168  2226 W libprocessgroup: kill(-24122, 9) failed: No such process
10-29 07:22:17.090  2168  2226 I libprocessgroup: Successfully killed process cgroup uid 10187 pid 24122 in 21ms
10-29 07:22:17.102  2168 10504 I ActivityManager: Killing 18355:com.android.chrome:sandboxed_process0/u0a155i411 (adj 906): empty #17
10-29 07:22:17.110  2168  2226 W libprocessgroup: Failed to open process cgroup uid 99411 pid 18355: No such file or directory
10-29 07:22:17.110  2168  2226 E libprocessgroup: Error encountered killing process cgroup uid 99411 pid 18355: No such file or directory
10-29 07:22:17.121 14392 14392 I Zygote  : Process 18355 exited due to signal (9)
```

**Comment by gottadiveintopython** [comment]
ありがとうございます。見るにどうやら64bit版のapkに32bit版の.soファイルが入り込んでしまったようです。これに関しては心当たりがあるのですぐに直せると思いますが、いま、amazonで注文したandroid端末が届けられるのを待っている最中なので、せっかくなのでそれで動作testした後にアプリを更新しようと考えてます。なのでそれまで待ってもらえたらと思います。

もし今すぐver0.0.2を使いたいのなら私が動作確認済みのarmeabi-v7a版を使ってください。その為の手順ですが

- `adb shell getprop | grep cpu` と打ってarmeabi-v7aに対応している確認。
- アプリのデータを消さないようにアプリをuninstall。(adbを使えばできるようです)
- ver0.0.2のarmeabi-v7a版をinstall

でできると思います。またもしver0.0.1に戻したいなら最後の手順でver0.0.1のarm64-v8a版をinstallです。(多分 @okajun35 さんの端末はarm64-v8aだと思うので)

**Comment by okajun35** [comment]
v0.0.3で正常に動作することを確認しました。
対応ありがとうございました。
